app = "flowai"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  DJANGO_SECRET_KEY = "7P.>?Jjw_qMeUX=SW5l;{i]}<H9?t|MmxT}tkO8s0qc_hNpQ9|"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024