app = "flowai"

[build]
  dockerfile = "Dockerfile"

[deploy]
  release_command = "python manage.py migrate"

[env]
  PORT = "8000"
  DJANGO_SECRET_KEY = "7P.>?Jjw_qMeUX=SW5l;{i]}<H9?t|MmxT}tkO8s0qc_hNpQ9|"
  DJANGO_SETTINGS_MODULE = "flowai.settings"

[processes]
  web = "gunicorn -c gunicorn.conf.py flowai.wsgi:application"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["web"]

[[statics]]
  guest_path = "/app/staticfiles"
  url_prefix = "/static"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024